# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Code\PyQt\freq\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.p10 = QtWidgets.QPushButton(Form)
        self.p10.setObjectName("p10")
        self.gridLayout.addWidget(self.p10, 3, 0, 1, 1)
        self.p1000 = QtWidgets.QPushButton(Form)
        self.p1000.setObjectName("p1000")
        self.gridLayout.addWidget(self.p1000, 3, 3, 1, 1)
        self.p100 = QtWidgets.QPushButton(Form)
        self.p100.setObjectName("p100")
        self.gridLayout.addWidget(self.p100, 3, 1, 1, 2)
        self.freq_le = QtWidgets.QLineEdit(Form)
        self.freq_le.setObjectName("freq_le")
        self.gridLayout.addWidget(self.freq_le, 0, 2, 1, 1)
        self.freq_lb = QtWidgets.QLabel(Form)
        self.freq_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.freq_lb.setObjectName("freq_lb")
        self.gridLayout.addWidget(self.freq_lb, 0, 1, 1, 1)
        self.start = QtWidgets.QPushButton(Form)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 1, 1, 1, 2)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.p10.setText(_translate("Form", "+10Hz"))
        self.p1000.setText(_translate("Form", "+1000Hz"))
        self.p100.setText(_translate("Form", "+100Hz"))
        self.freq_lb.setText(_translate("Form", "frequency"))
        self.start.setText(_translate("Form", "Start"))
